### ISSUE TITLE
[question] 10. Javascript: Classname instead globalState

### ISSUE THREAD

**Issue by gitbreaker222** [adamsilver/maintainablecss.com#5]
When creating an element from a _JS-Class_, the current approach is to either use explicit module-class-names for every _instance_ or absolute global state:

```javascript
var module1Collapser = new Collapser(element1, {
  cssHideClass: 'moduleA-isHidden'
});

var module2Collapser = new Collapser(element2, {
  cssHideClass: 'moduleB-isHidden'
});
```

```css
.moduleA-isHidden,
.moduleB-isHidden {
  display: none;
}
```

```css
.globalState-isHidden {
  display: none;
}
```
___

But we already have a (JS) class name _"Collapser"_, so the first thing I would concider is using that instead of global state.

```css
/* selecting every "Collapser" instance that is hidden*/
.Collapser-isHidden {
  display: none;
}

/* if a specific Collapser-instance should look differnt */
.collapserA-isHidden {
  display: block;
  height: 0;
}
```
# Question:

Are there any arguments agains JS-Class-name instead global state (assuming global state can be used for really everything)?

## Proposal:

Replace `.globalState` with the js-class-name `.Collapser`.

___

The [_Javascript_ chapter](https://maintainablecss.com/chapters/javascript/) sais:

> […] the global class will be referenced from within […] However, this approach doesn't always make sense. We may have two different modules that _behave_ the same, but _look_ different, which is something we've discussed in [State](https://maintainablecss.com/chapters/state/).

In _State:_

> […] whilst states might be common, associated styles might not. For example, an empty basket has a gray background, where as an empty search has an absolutely-positioned image.  
What about reusing state?
Sometimes, we may in fact want to reuse state across modules or components. For example, toggling an element's visibility. This is discussed in more detail in the chapter entitled Javascript.

**Comment by gitbreaker222** [comment]
Thanks for your reply :) I think this goes in the right direction, but maybe needs more background information *(why/how show js-components for cases, where js is disabled?)*

Maybe it is more clear, if we could stick to [the collapser example from the javascript chapter](https://maintainablecss.com/chapters/javascript/)

I think I can be more precise now after thinking deeper. Can we change this part?

> The trade-off is that this list could grow quickly (or use a mixin). And every time we add behavior, we need to update the CSS. A small change, but a change nonetheless. In this case we might consider a ~~global state~~ **JS-module-name** class.

The code example would then be:

```css
.Collapser-isHidden {
  display: none;
}
```

... because we can then write CSS for all Collapsers, instead of putting weight on the "global-CSS-space". Let me know, if I can make a fork/pull-request for a specific diff.
